#ifndef TEST
#define TEST
#include <stdio.h>
#include <iostream>
#include <cstddef>
#include <cstdlib>
#include <string>
#include <cstring>
#include <fstream>
#include <istream>
#include <vector>
#include <array>
#include <list>
#include <tuple>
#include <queue>
#include <map>
#include <thread>
#include <future>
#include <mutex>
#include <cassert>
#include <ios>
#include <functional>
#include <atomic>
#include <condition_variable>
#include <cfloat>
#include <CL/opencl.h>
#include <CL/cl.h>
#include <CL/cl.hpp>
#include <clAmdBlas.h>
#include <clBLAS.h>
#endif